@startuml c4-container

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

left to right direction

HIDE_STEREOTYPE()
SHOW_PERSON_OUTLINE()

System_Ext(usuario, "Software Cliente")

System_Boundary(c1, "Sistema de Avaliação Docente (AD)") {
  Container(cli, "API", "Spring Boot", "Geração e consulta de análises")
  ContainerDb(db, "Armazenamento", "NoSQL", "Análises")
}


Rel_D(cli, db, "Persiste/recupera análise")
Rel_D(usuario, cli, "Requisita/consulta análises")

@enduml
