@startuml c4-component
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

UpdateBoundaryStyle($bgColor="gold", $fontColor="brown", $borderColor="brown")
UpdateSystemBoundaryStyle($bgColor="gold", $fontColor="white", $borderColor="white")

System(cliente, "Cliente externo")

Container_Boundary(c3, "Terceiros") {
    Component(comp1, "Domínio", "Regras fixas/interfaces", "Parte invariante")
    Component(comp2, "Resolução", "Implementa uma resolução", "Carregado dinamicamente")
    Rel(comp2, comp1, "Implementa", "")
}

System_Boundary(c1, "Outra fronteira (agrupa apenas)", $tags="v1") {
    Component(comp6, "Conversores", "JSON/Objeto", "Conversão entre formatos")
    Component(comp7, "Serviços", "Casos de Uso", "Implementação")
    Component(comp8, "Repositórios", "Entidades", "Implementação")
    Rel(comp7, comp1, "usa", "importa")
    Rel(comp8, comp1, "usa", "importa")
    Rel(comp6, comp1, "usa", "importa")
}

System_Boundary(c2, "Mais um agrupador para ilustrar", $tags="v1") {
    Component(comp3, "REST API", "Controllers", "Recebe requisições")
}

System_Boundary(c4, "Outra fronteira", $tags="v2") {
    ComponentDb(comp5, "Componente 5", "subtítulo", "descricao")
}

Rel(comp3, comp5, "usa", "algum detalhe adicional?")

AddBoundaryTag("v1", $bgColor="lightgreen", $fontColor="green", $borderColor="green")
AddElementTag("v1", $bgColor="lightred", $fontColor="red", $borderColor="red")

AddBoundaryTag("v2", $bgColor="LightGray", $fontColor="green", $borderColor="green")
AddElementTag("v2", $bgColor="LightBlue", $fontColor="red", $borderColor="red")

Rel_L(comp3, comp7, "usa", "")
Rel(cliente, comp3, "usa", "HTTPS")

Component(comp9, "Resolução X", "Implementação", "Carregado dinamicamente")
Component(comp10, "Resolução Y", "Implementação", "Carregado dinamicamente")

Component(comp11, "Loader", "Carrega resolução", "Disponibiliza resolução\nem tempo de execução")

Rel_U(comp9, comp1, "Depende de", "")
Rel_U(comp10, comp1, "Depende de", "")
Rel_D(comp7, comp11, "carrega", "")


@enduml
