@startuml c4-contexto

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

left to right direction

HIDE_STEREOTYPE()
SHOW_PERSON_OUTLINE()

System(docente, "AD", "Avaliação de desempenho")

System_Ext(usuario, "Software Cliente", "Ecossistema UFG")

Rel(usuario, docente, "Requisita/consulta análises\nde desempenho de docente", "")

@enduml
