@startuml c4-component
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

UpdateBoundaryStyle($bgColor="gold", $fontColor="brown", $borderColor="brown")
UpdateSystemBoundaryStyle($bgColor="gold", $fontColor="white", $borderColor="white")

System(cliente, "Cliente externo")

Component(comp1, "Domínio", "Regras fixas/interfaces", "Parte invariante")

Component(conversores, "Conversores", "JSON/Objeto", "Conversão entre formatos")
Component(servicos, "Casos de Uso", "package", "Implementação das funções")
Component(repos, "Repositórios", "Entidades", "Implementação")
Rel(servicos, comp1, "usa", "importa")
Rel(repos, comp1, "usa", "importa")
Rel(conversores, comp1, "usa", "importa")
Rel(servicos,conversores, "usa")

Component(rest, "REST API", "Controllers", "Recebe requisições")

ComponentDb(db, "Armazenamento", "MongoDB", "Análises e dados administrativos")

Rel(repos, db, "usa")

AddBoundaryTag("v1", $bgColor="lightgreen", $fontColor="green", $borderColor="green")
AddElementTag("v1", $bgColor="lightred", $fontColor="red", $borderColor="red")

AddBoundaryTag("v2", $bgColor="LightGray", $fontColor="green", $borderColor="green")
AddElementTag("v2", $bgColor="LightBlue", $fontColor="red", $borderColor="red")

Rel_L(rest, servicos, "usa", "")
Rel(cliente, rest, "usa", "HTTPS")

Container_Boundary(loader, "Repositório de resoluções") {
    Component(comp9, "Resolução X", "Implementação de X", "Carregado dinamicamente")
    Component(comp10, "Resolução Y", "Implementação de Y", "Carregado dinamicamente")
}

Component(comp11, "Loader", "Carrega resolução", "Disponibiliza resolução\nem tempo de execução")

Rel_U(comp9, comp1, "Depende de", "")
Rel_U(comp10, comp1, "Depende de", "")
Rel_D(servicos, comp11, "carrega", "")

Rel(comp11, comp9, "Carrega")
Rel(comp11, comp1, "Depende de")


@enduml
