@startuml dominio-code

hide circle
hide methods
hide empty members

skinparam class {
    BackgroundColor White
    ArrowColor Black
    BorderColor #505050
}

class "Análise" as Analise {
    data
}

class Resultado {
    nome do indicador
    valor
}

rectangle "regras de negócio" #line.dashed {

    class "Resolução" as Resolucao {
        nome
        versão
        ---
        avalia&#40;Contexto&#41; : [Resultado]
    }

    interface Indicador {
        <<PK>> nome : String
        avalia&#40;Contexto&#41; : Resultado
    }
}
class Contexto {}
class Docente {}

Resolucao "1" --> "1..*" Indicador : Definida\npor


Contexto --> "1..*" Resultado

Analise -up-> "1" Docente
Analise -right-> "1" Contexto : Entrada
Analise --> "1" Resolucao
Analise -down-> "1" Resultado
@enduml