@startuml dominio

hide circle
hide methods
hide empty members

skinparam class {
    BackgroundColor White
    ArrowColor Black
    BorderColor #505050
}

class ResolucaoId {
  nome
  versao
}

class "Análise" as Analise {
    instante
}

class Resultado {
    nome do indicador
    valor
}

class Contexto {
  valorPara&#40;nome&#41; : Resultado
}

class Docente {}

class "Avaliação" as Avaliacao {
  data
  requisitada por
}

Avaliacao -right-> "1" Docente
Avaliacao -down-> "1" Analise

rectangle "regras de negócio" #line.dashed {

    interface "Resolução" as ResolucaoCodigo {
        nome
        versão
        ---
        avalia&#40;Contexto&#41; : Analise
        indicadores&#40;&#41; : Set<String>
    }

    interface Indicador {
        nome : String
        avalia&#40;Contexto&#41; : Resultado
    }
}

ResolucaoCodigo "1" --> "1..*" Indicador : Definida\npor


Contexto --> "1..*" Resultado

Analise -right-> "1" Contexto : entrada
Analise -right-> "1" Contexto : saída
Analise --> "1" ResolucaoId

class Plugin {
  arquivo
  nomeResolucao
  versaoResolucao
}

interface ResolucaoRepository {
  cria&#40;plugin&#41;
  busca&#40;nome, versao&#41; : ResolucaoId
}

interface AvaliacaoRepository {
  busca&#40;docente, data&#41; : [Analise]
  ultimaPara&#40;docente&#41; : Analise
}


@enduml
